### ISSUE TITLE
Trying out the library and difficulty to execute an entrypoint call

### ISSUE THREAD

**Issue by brunolune** [moneytrackio/tezart#76]
Using a simple increment/decrement contract on hangzhounet (KT1QLqPN8us3LpgqSR9BgdF8bwJ8vJBjhfwV)
The contract is found, as well as entrypoints, storage ... However I have not been able to execute an increment() call so far.
Here is the code: 
Future<void> increment() async {
    const String secretKey =
        "edsk...";
    final source = Keystore.fromSecretKey(secretKey);
   var rpcUrl = "https://hangzhounet.api.tez.ie";
    final client = TezartClient(rpcUrl);
    const contractAddress = "KT1QLqPN8us3LpgqSR9BgdF8bwJ8vJBjhfwV";
    final rpcInterface = client.rpcInterface;
    final contract =
        Contract(contractAddress: contractAddress, rpcInterface: rpcInterface);
     final callContractOperationsList = await contract.callOperation(
      entrypoint: 'increment',
      params: 1,
      source: source,
    );
    await callContractOperationsList.estimate(); // computes the counters, storage limits, gas limits and fees
    await callContractOperationsList.execute();
    await callContractOperationsList.monitor();
}

I got this error:
...
I/flutter ( 8676): 2021-12-25 23:49:16.259955[INFO] - RpcInterface : request for forgeOperations [ chain:main, level:head]
I/flutter ( 8676): 2021-12-25 23:49:16.260530[INFO] - RpcInterface : request for branch [ chain:main, level:head]
I/flutter ( 8676): 2021-12-25 23:49:16.260718[INFO] - TezartHttpClient : request to get from path: chains/main/blocks/head/hash
I/flutter ( 8676): 2021-12-25 23:49:16.925714[INFO] - TezartHttpClient : request to post to path: chains/main/blocks/head/helpers/forge/operations
I/flutter ( 8676): 2021-12-25 23:49:18.189721[INFO] - RpcInterface : request for injectOperation [ chain:main]
I/flutter ( 8676): 2021-12-25 23:49:18.189933[INFO] - TezartHttpClient : request to post to path: injection/operation?chain=main
I/flutter ( 8676): 2021-12-25 23:49:18.418852[INFO] - Operation : request to monitorOperation opSz2QbwPvRz7Xu7mshvpxTMinjcUgsRpRkcFWG12MDihFvhZw2
I/flutter ( 8676): 2021-12-25 23:49:18.419441[INFO] - TezartHttpClient : request to get from path: chains/main/blocks/head
I/flutter ( 8676): 2021-12-25 23:49:20.836868[INFO] - TezartHttpClient : request to get from path: chains/main/blocks/BMMAXD6o8CrareoHhdrS1JwAueH1J2toYr99mL5LrfRXxASkujB/operation_hashes/3
I/flutter ( 8676): 2021-12-25 23:49:23.286202[INFO] - TezartHttpClient : request to get from path: chains/main/blocks/BKksBHnmgyo61tsmySsj8M5a4UeXwVc2JkjLHQFBwfo3YsNYsKQ/operation_hashes/3
I/flutter ( 8676): 2021-12-25 23:49:58.009417[INFO] - TezartHttpClient : request to get from path: chains/main/blocks/BLH2Q86aVop56vuFSd9wK3y9XxT1bo3fBh3CUwpf1Wg26jzKpwQ/operation_hashes/3
E/flutter ( 8676): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: TezartNodeError: got code monitoringTimedOut with msg Monitoring the operation opSz2QbwPvRz7Xu7mshvpxTMinjcUgsRpRkcFWG12MDihFvhZw2 timed out.
E/flutter ( 8676): #0      OperationsMonitor.monitor
package:tezart/…/impl/operations_monitor.dart:41
E/flutter ( 8676): <asynchronous suspension>
E/flutter ( 8676): #1      OperationsList.monitor
package:tezart/…/impl/operations_list.dart:205
E/flutter ( 8676): <asynchronous suspension>
E/flutter ( 8676): #2      _MyHomePageState.increment
package:tezartdapp/main.dart:74
E/flutter ( 8676): <asynchronous suspension>
E/flutter ( 8676):

**Comment by Pierre-Michard** [comment]
Hi Bruno, 
From the logs it seems that the operation has been correctly applied but the monitoring timeout before it could be included into a block. Nevertheless, I see this operation nowhere in the hangzhounet network.
We should: 
- reproduce this issue.
- retrieve the content of the response of the apply operation in order to check what goes wrong.

**Comment by brunolune** [comment]
Hello Pierre,
Thanks for your reply ... looking forward to use tezart for my tezos dapp ...
I made a new repo with the code if you want to try to reproduce the error
https://github.com/brunolune/tezartdapp
I provided the output of the console in the README.
Thanks,
Bruno

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Pierre-Michard** [comment]
Thank-you for the code!
I've been doing some tests. The issue comes from the automatic computation of the fee applied to the transaction. 
We are computing a too low fee, which lead the node to filter-out the transaction although it a valid transaction. 
We will investigate this issue. 
In the meantime, a workaround is to define a custom fee:

```
final callContractOperationsList = await contract.callOperation(
    entrypoint: 'increment',
    params: 1,
    source: source,
    customFee: 1000,
  );

```
